### ISSUE TITLE
opschonen flux-beheer: remove unnecesserary or deprecated deployments

### ISSUE THREAD

**Issue by julian9499** [WISVCH/flux-beheer#49]

**Comment by praseodym** [comment]
Which ones are deprecated?

**Comment by julian9499** [comment]
CH TV, Payments for now. With the current migration going we will soon have other deprecated ones as well. Events is currently on 0 replicas and has been transferred, but we  can still consider it as backup if necessary for example.

**Comment by praseodym** [comment]
I see! I'd just remove all deployments that have been migrated, you can always get them back from Git if needed.

**Comment by julian9499** [comment]
Yeah you're right actually. I will include them with the next migration
